# only for local development

version: "3"

services:
  web:
    build:
      context: .
      dockerfile: docker/Containerfile
    container_name: brnoblend_web
    hostname: web
    command: "/bin/bash"
    #command: "uvicorn src.app.api:app --host 0.0.0.0 --port 5020 --reload"
    stdin_open: true
    tty: true
    working_dir: /opt/brno-blend/src
    ports:
      - "5020:5020"
    volumes:
      - .:/opt/brno-blend:z
    environment:
      - PYTHONPATH=/opt/brno-blend
    env_file:
      - "files/env"
    depends_on:
      - database

  database:
    image: postgres:alpine
    container_name: brnoblend_db
    hostname: database
    restart: always
    env_file:
      - "files/env"
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  database:
