# this containerfile is only for local developement
# context is git root

FROM fedora:40

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN dnf -y update && \
    # build deps and debug tools
    dnf -y install htop \
                   make \
                   wget \
                   net-tools \
                   iputils \
                   vim \
                   mlocate \
                   git \
                   sudo \
                   python3-ipdb \
                   findutils \
                   python3-pip \
                   fzf \
                   util-linux \
    && dnf clean all


COPY src/requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

#COPY src /tmp_project/src
#WORKDIR /tmp_project/src

#ENV PYTHONPATH /tmp_project

#RUN ./manage.py create-db
#RUN rm -rf /src
