# context is git root

FROM fedora:40

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN dnf -y update && \
    # build deps and debug tools
    dnf -y install htop \
                   make \
                   wget \
                   net-tools \
                   iputils \
                   vim \
                   mlocate \
                   git \
                   sudo \
                   python3-ipdb \
                   findutils \
                   python3-pip \
                   fzf \
                   util-linux \
    && dnf clean all


COPY src/requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt
